### ISSUE TITLE
"uninitialized constant XBee (NameError)"

### ISSUE THREAD

**Issue by philask** [exsilium/ruby-xbee#1]
Example:

```
macpro:~/Development/ruby-xbee $ xbeeinfo.rb
/Library/Ruby/Gems/2.0.0/gems/ruby-xbee-1.2.0/lib
/Library/Ruby/Gems/2.0.0/gems/ruby-xbee-1.2.0/bin/xbeeinfo.rb:83:in '<top (required)>': uninitialized constant XBee (NameError)
    from /usr/local/bin/xbeeinfo.rb:23:in 'load'
    from /usr/local/bin/xbeeinfo.rb:23:in '<main>'
macpro:~/Development/ruby-xbee $ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.7, 1.2.0)
CFPropertyList (2.3.2, 2.2.8)
daemons (1.2.3)
eventmachine (1.0.8)
ffi (1.9.10)
io-console (0.4.2)
json (1.8.3, 1.7.7)
libxml-ruby (2.8.0, 2.6.0)
mini_portile (0.6.2)
minitest (5.8.2, 4.3.2)
nokogiri (1.5.6)
power_assert (0.2.5)
psych (2.0.15, 2.0.0)
rack (1.6.4)
rack-protection (1.5.3)
rake (10.4.2, 0.9.6)
rdoc (4.2.0, 4.0.0)
ruby-debug-ide (0.6.0)
ruby-xbee (1.2.0)
rubygems-update (2.5.0)
rubyserial (0.2.4)
serialport (1.3.1)
sinatra (1.4.6)
sqlite3 (1.3.11, 1.3.7)
test-unit (3.1.5, 2.0.0.0)
thin (1.6.4)
tilt (2.0.1)
macpro:~/Development/ruby-xbee $ 
```

**Comment by exsilium** [comment]
Thanks for the report, a bug in the gemspec. I'll push a fix soon. Cheers!

**Comment by exsilium** [comment]
1.2.1 has been published to address the NameError issue.

**Comment by philask** [comment]
Superb, works perfectly now, thank you.  FYI. am using on a Rasberry Pi B (Raspbian Jessie).

`Linux raspberrypi 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux`
